name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: atomverse
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SERVER_SSH_PASSPHRASE }}

    steps:
      - name: Check env presence
        run: |
          [ -n "$SSH_HOST" ] && echo "SSH_HOST OK" || echo "SSH_HOST EMPTY"
          [ -n "$SSH_USERNAME" ] && echo "SSH_USERNAME OK" || echo "SSH_USERNAME EMPTY"
          [ -n "$SSH_PORT" ] && echo "SSH_PORT OK" || echo "SSH_PORT EMPTY"
          [ -n "$SSH_KEY" ] && echo "SSH_KEY OK" || echo "SSH_KEY EMPTY"

      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          passphrase: ${{ env.SSH_PASSPHRASE }}
          script: |
            cd atomverse
            git pull origin main
            composer install --no-dev --optimize-autoloader
            npm ci
            npm run build
            php artisan migrate --force
            php artisan optimize